on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches: main

jobs:
  snake:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            build/snake.svg?&color_snake=orange&color_dots=##393939,#0e4429,#006d32,#26a641,#39d353
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: push snake.svg
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: snake
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
